# Generated by Django 3.0.9 on 2023-04-19 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Debtentry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Auto Loan', 'Auto Loan'), ('Personal Loan', 'Personal Loan'), ('Student Loan', 'Student Loan'), ('Mortgage', 'Mortgage'), ('Medical Loan', 'Medical Loan'), ('Taxes', 'Taxes'), ('Other', 'Other')], max_length=255)),
                ('name', models.CharField(max_length=128)),
                ('currBalance', models.FloatField()),
                ('TotalBalance', models.FloatField()),
                ('apr', models.FloatField()),
                ('minPayment', models.FloatField()),
                ('dueDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
