# Generated by Django 3.0.9 on 2023-02-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addTransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseentry',
            name='transactionDate',
            field=models.DateField(),
        ),
    ]
